id: Av2ngIKZNyIxaw
secret: o1AsNaLJPe94ofNUuKaK-zVCE4Y
password: Dreams@22
agent: george likes memes so will post memes
username: GeorgeIsABot
sub: test
author: GeorgeIsABot
threadTitle: A Place to Test for George
ImgurAuth: Client-ID 71ce1c0e0c972b3
GiphyAuth: vNtiE6s0fhNVBdiITvE9ycDMQkyY4F6q
